name: Matrix Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy ${{ matrix.deployment.environment }} - ${{ matrix.deployment.region }}
    runs-on: ubuntu-latest
    environment: development

    strategy:
      matrix:
        include:
          - environment: ${{vars.test}}
            region: ap-south-1
            replicas: 1

          - environment: staging
            region: ap-south-1
            replicas: 2

          - environment: production
            region: ap-south-1
            replicas: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show deployment configuration
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "Region: ${{ matrix.region }}"
          echo "Replicas: ${{ matrix.replicas }}"

      - name: Deploy
        run: |
          echo "Deploying to ${{ matrix.environment }}"
          echo "Region: ${{ matrix.region }}"
          echo "Replicas: ${{ matrix.replicas }}"
